# Generated by Django 2.2.13 on 2020-10-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='ligue',
            new_name='league',
        ),
    ]
