# Generated by Django 2.2.13 on 2020-10-28 18:56

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='refree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=120)),
                ('rimage', models.ImageField(blank=True, null=True, upload_to=players.models.upload_image_path)),
                ('rage', models.PositiveIntegerField(blank=True, null=True)),
                ('dob', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
    ]
