# Generated by Django 2.2.13 on 2020-10-29 10:54

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_refree'),
    ]

    operations = [
        migrations.CreateModel(
            name='stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=120)),
                ('simage', models.ImageField(blank=True, null=True, upload_to=players.models.upload_image_path)),
                ('cap', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
    ]
