# Generated by Django 2.2.13 on 2020-10-28 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_refree'),
        ('matches', '0003_auto_20190729_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refree', to='players.refree'),
        ),
    ]
