# Generated by Django 2.2.13 on 2020-10-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_stadium'),
        ('matches', '0004_match_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stad', to='players.stadium'),
        ),
    ]
